/**
 * Output adapters: NCRP-shaped packet, 1930 read-aloud card, case PDF,
 * guardian handoff code. Full spec: docs/BUILD_BRIEF.md, section 5.
 *
 * Reminder: buildNcrpPacket produces a packet for the user to review and
 * self-submit — NCRP has no public API, this must never claim to have
 * submitted anything on the user's behalf.
 */

import { jsPDF } from "jspdf";
import { composeNarrative } from "./narrative.js";
import { inferTaxonomy } from "./taxonomy.js";

/**
 * Builds a JSON object whose keys mirror the NCRP field list.
 * This is for the user to review/download — NOT an actual submission.
 * @param {import('../state/machine.js').Case} caseObj
 * @returns {object}
 */
export function buildNcrpPacket(caseObj) {
  const tx = caseObj.transactions[0] ?? {};
  const taxonomy = caseObj.channel
    ? inferTaxonomy(caseObj.channel, tx)
    : { category: "Financial Fraud", subCategory: "UPI Related Frauds" };

  return {
    complaintCategory: taxonomy.category,
    complaintSubCategory: taxonomy.subCategory,
    stateUt: caseObj.stateUt ?? "Not determined",
    incidentDate: tx.timestamp ?? null,
    fraudAmount: tx.amount ?? 0,
    currency: "INR",
    bankOrWallet: tx.bank ?? "Unknown",
    transactionReference: tx.utr ?? null,
    beneficiaryVpa: tx.beneficiaryVpa ?? null,
    accountTail: tx.accountTail ?? null,
    incidentDescription: composeNarrative(caseObj),
    caseReferenceId: caseObj.id,
    createdAt: caseObj.openedAt,
    _disclaimer: "This is a pre-filled packet for self-submission. It has NOT been submitted to cybercrime.gov.in on your behalf.",
  };
}

/**
 * Four short lines readable aloud to a 1930 operator.
 * @param {import('../state/machine.js').Case} caseObj
 * @returns {string[]}
 */
export function buildHelplineCard(caseObj) {
  const tx = caseObj.transactions[0] ?? {};
  const amount = tx.amount ? `Rs.${tx.amount.toLocaleString("en-IN")}` : "Unknown amount";
  const bank = tx.bank ?? "Unknown bank";
  const utr = tx.utr ?? "No reference";
  const caseId = caseObj.id.slice(0, 8);

  return [
    `Case ID: ${caseId}`,
    `${amount} debited from ${bank} account`,
    `UPI Reference: ${utr}`,
    `Filed via Rok at ${caseObj.openedAt ? new Date(caseObj.openedAt).toLocaleString("en-IN") : "unknown time"}`,
  ];
}

/**
 * Generates a PDF summary of the case using jsPDF.
 * @param {import('../state/machine.js').Case} caseObj
 * @returns {Blob}
 */
export function buildCasePdf(caseObj) {
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 20;
  const contentWidth = pageWidth - margin * 2;
  let y = 25;

  /* Title */
  doc.setFontSize(18);
  doc.setFont("helvetica", "bold");
  doc.text("Rok - Financial Fraud Case Report", margin, y);
  y += 10;

  /* Disclaimer */
  doc.setFontSize(8);
  doc.setFont("helvetica", "italic");
  doc.text("Not an official Government of India document. For self-submission to cybercrime.gov.in.", margin, y);
  y += 12;

  /* Case details */
  doc.setFontSize(11);
  doc.setFont("helvetica", "bold");
  doc.text("Case Details", margin, y);
  y += 7;

  const packet = buildNcrpPacket(caseObj);
  const fields = [
    ["Case Reference", caseObj.id],
    ["Opened At", caseObj.openedAt ?? "Unknown"],
    ["Category", packet.complaintCategory],
    ["Sub-category", packet.complaintSubCategory],
    ["Bank/Wallet", packet.bankOrWallet],
    ["Amount", `Rs. ${packet.fraudAmount.toLocaleString("en-IN")}`],
    ["Transaction Reference", packet.transactionReference ?? "N/A"],
    ["Beneficiary VPA", packet.beneficiaryVpa ?? "N/A"],
    ["Account Ending", packet.accountTail ?? "N/A"],
    ["State/UT", packet.stateUt],
  ];

  doc.setFontSize(10);
  for (const [label, value] of fields) {
    doc.setFont("helvetica", "bold");
    doc.text(`${label}:`, margin, y);
    doc.setFont("helvetica", "normal");
    doc.text(String(value), margin + 50, y);
    y += 6;
  }

  y += 6;

  /* Narrative */
  doc.setFontSize(11);
  doc.setFont("helvetica", "bold");
  doc.text("Incident Description", margin, y);
  y += 7;

  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  const narrativeLines = doc.splitTextToSize(packet.incidentDescription, contentWidth);
  doc.text(narrativeLines, margin, y);
  y += narrativeLines.length * 5 + 10;

  /* Footer */
  doc.setFontSize(8);
  doc.setFont("helvetica", "italic");
  doc.text("Generated by Rok - hackathon proof of concept. Not an official Government of India platform.", margin, y);

  return doc.output("blob");
}

/**
 * Generates a short alphanumeric handoff code and stores the case in
 * localStorage under that key.
 *
 * DEMO SIMPLIFICATION: This is a localStorage-backed, same-browser/
 * same-device-only mechanism. A real implementation would need a relay
 * server, which is out of scope for this POC. See AGENTS.md security
 * posture section for the rationale.
 *
 * @param {import('../state/machine.js').Case} caseObj
 * @returns {string}
 */
export function buildGuardianHandoffCode(caseObj) {
  const code = Math.random().toString(36).slice(2, 8).toUpperCase();
  try {
    localStorage.setItem(`rok:handoff:${code}`, JSON.stringify(caseObj));
  } catch {
    /* localStorage may be full or unavailable — fail silently for the demo. */
  }
  return code;
}

/**
 * Retrieves a case from localStorage using a handoff code.
 * @param {string} code
 * @returns {import('../state/machine.js').Case | null}
 */
export function retrieveHandoffCase(code) {
  try {
    const data = localStorage.getItem(`rok:handoff:${code.toUpperCase()}`);
    return data ? JSON.parse(data) : null;
  } catch {
    return null;
  }
}
